event-listener.name=http
http-event-listener.log-created=false
http-event-listener.log-completed=true
http-event-listener.connect-ingest-uri=http://audit-receiver:8090/api/v1/audit
http-event-listener.connect-retry-count=1
http-event-listener.connect-retry-delay=1s
http-event-listener.connect-max-delay=5s
